name: Deploy Package to GitHub Container Registry

on:
  workflow_run:
    workflows: ['Code Quality']
    types:
      - completed

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/diogocezar/pizzaiolo:${{ steps.package-version.outputs.current-version}}
          build-args: github_token=${{secrets.GITHUB_TOKEN}}
