name: 'Publish Docker'

on:
  push:
    branches: [main]

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/diogocezar/pizzaiolo:latest
          docker run ghcr.io/diogocezar/pizzaiolo:latest
          docker push ghcr.io/diogocezar/pizzaiolo:latest
