export enum LogType {
  OPENED_PULL_REQUEST = 'OPENED_PULL_REQUEST',
  CLOSED_PULL_REQUEST = 'CLOSED_PULL_REQUEST',
  SUBMITTED_PULL_REQUEST = 'SUBMITTED_PULL_REQUEST',
  CREATED_PULL_REQUEST = 'CREATED_PULL_REQUEST',
  RESOLVED_PULL_REQUEST = 'RESOLVED_PULL_REQUEST',
  UNRESOLVED_PULL_REQUEST = 'UNRESOLVED_PULL_REQUEST',
}
